apiVersion: v1
kind: Secret
metadata:
  name: {{ include "xxl-job.fullname" . }}-database
  labels:
    {{- include "xxl-job.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.database.username | quote }}
  password: {{ .Values.database.password | quote }}

