# 生产环境配置
spring:
  cloud:
    nacos:
      discovery:
        server-addr: production-nacos-host:8848
        namespace: production-namespace
      config:
        server-addr: production-nacos-host:8848
        namespace: production-namespace

rocketmq:
  name-server: production-rocketmq-host:9876
