apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rocketmq.fullname" . }}-broker-config
  labels:
    {{- include "rocketmq.labels" . | nindent 4 }}
data:
  broker.conf: |
    brokerClusterName = {{ .Values.broker.clusterName }}
    brokerName = {{ .Values.broker.brokerName }}
    brokerId = {{ .Values.broker.brokerId }}
    deleteWhen = 04
    fileReservedTime = 48
    brokerRole = ASYNC_MASTER
    flushDiskType = ASYNC_FLUSH
    autoCreateTopicEnable = {{ .Values.broker.autoCreateTopicEnable }}
    namesrvAddr = {{ include "rocketmq.fullname" . }}-nameserver:{{ .Values.nameserver.service.port }}

