{{- if .Values.broker.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "rocketmq.fullname" . }}-broker-store
  labels:
    {{- include "rocketmq.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.broker.persistence.storageClass }}
  storageClassName: {{ .Values.broker.persistence.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.broker.persistence.size }}
{{- end }}

