apiVersion: v1
kind: Secret
metadata:
  name: {{ include "canal.fullname" . }}-mysql
  labels:
    {{- include "canal.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.mysql.username | quote }}
  password: {{ .Values.mysql.password | quote }}

