apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mysql.fullname" . }}-config
  labels:
    {{- include "mysql.labels" . | nindent 4 }}
data:
  my.cnf: |
    [mysqld]
    server-id = 101
    log-bin = mysql-bin
    binlog-format = ROW
    binlog-row-image = FULL
