{{- if and (eq .Values.database.type "mysql") (not .Values.database.mysql.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nacos.databaseSecretName" . }}
  labels:
    {{- include "nacos.labels" . | nindent 4 }}
type: Opaque
stringData:
  database: {{ .Values.database.mysql.database | quote }}
  username: {{ .Values.database.mysql.username | quote }}
  password: {{ .Values.database.mysql.password | quote }}
{{- end }}
