server:
  port: 10050

spring:
  application:
    name: coupon-hub-search
  config:
    import:
      - optional:nacos:coupon-hub-redis-dev.yaml?group=COUPON_HUB_GROUP&refreshEnabled=true
      - optional:nacos:coupon-hub-rocketmq-dev.yaml?group=COUPON_HUB_GROUP&refreshEnabled=true
      - optional:nacos:coupon-hub-springdoc-dev.yaml?group=COUPON_HUB_GROUP&refreshEnabled=true
      - optional:nacos:coupon-hub-knife4j-dev.yaml?group=COUPON_HUB_GROUP&refreshEnabled=true
      - optional:nacos:coupon-hub-elasticsearch-dev.yaml?group=COUPON_HUB_GROUP&refreshEnabled=true
      - optional:nacos:coupon-hub-search-dev.yaml?group=COUPON_HUB_GROUP&refreshEnabled=true
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER_ADDR:192.168.252.4:30848}
        namespace: ${NACOS_NAMESPACE:coupon-hub-dev}
        group: COUPON_HUB_GROUP
      config:
        server-addr: ${NACOS_SERVER_ADDR:192.168.252.4:30848}
        namespace: ${NACOS_NAMESPACE:coupon-hub-dev}
        group: COUPON_HUB_GROUP
        file-extension: yaml
      password: ${NACOS_PASSWORD:123456}
